auction_site heroku/config/routes.rb
Rails.application.routes.draw do

  get 'bids/new'

  get 'bids/create'

resources :users, only: [:show, :new, :create, :destroy] do#only specifies the methods in the controller, because if not it would also create something like index, which we don't need in this controller
	resources :products, except: [:edit, :update]
end

get '/products/:id/bids/new', to: 'bids#new'
post '/products/:id/bids', to: 'bids#create', as: :product_bids
get '/products/:id/bids', to: 'bids#index', as: :product_bids_all


end

#undefined method 'products_bids_path' error => wants that our create action has a products_bids_path

auction_site heroku/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

auction_site heroku/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :product
  validate :new_bid_must_be_above_min_bid, :new_bid_must_be_above_highest_bid, on: :create

  def new_bid_must_be_above_min_bid
  	@new_bid = product.bids.new(user_id: user_id, amount: amount)
    @min = @new_bid.product.min_bid
  	if @new_bid < @min
  		errors.add(:new_bid, "cannot be lower than the price")
  	end
  end

  def new_bid_must_be_above_highest_bid
  	@new_bid = product.bids.new(user_id: user_id, amount: amount)
  	if @new_bid < Bid.last
  		errors.add(:new_bid, "cannot be lower than the highest bid")
  	end
  end
end

auction_site heroku/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bids
end

auction_site heroku/app/models/user.rb
class User < ApplicationRecord
	validates :email, uniqueness: true, presence: true
	has_many :products
end
#table contains instances of the model
#model -- singular

auction_site heroku/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

auction_site heroku/app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def index
  	product = Product.find_by(id: params[:id])
  	@bids = product.bids
    @bids.order("amount :desc")
  end

  def new
  end

  def create
  	amount = params[:amount]
  	user_id = (User.find_by(email: params[:email])).id
  	product = Product.find_by(id: params[:id])
  	@new_bid = product.bids.new(user_id: user_id, amount: amount)
    @min = @new_bid.product.min_bid
	  	if @new_bid.save
	  		redirect_to product_bids_all_path(product.id)
	  	else
	  		render text => "Bid cannot be made"
	  	end
  end

end

#Strong params are only for form_for

auction_site heroku/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @user = User.find_by(id: params[:user_id])
    @product = Product.find_by(id: params[:id])
    winner_id = Bid.last.user_id
    winner_id = User.find_by(id: winner_id).name
    @winner = winner_id
  end

  def new
    @user = User.find_by(id: params[:user_id])
    @new_product = Product.new
  end

  def create
    user = User.find_by(id: params[:user_id])
    @product = user.products.new(product_params)
    if product.save
      redirect_to user_products_path(user)
    else 
      render text => "Product could not be saved"
    end

  end

  def destroy
  end

  private
  def product_params #STRONG PARAMETERS: Grabs all the parameters for product that would normally go in the create action and inserts into this method, that simplifies the params code for a product
    params.require(:product).permit(:title, :description, :min_bid, :deadline)
  end
  #when you have a nested path and you need to connect another variable into the form, you create the instance variable, and you join it by the "user.product" example, and you use strong params
end

auction_site heroku/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find_by(id: params[:id])
  end

  def new
  	@new_user = User.new
  	render 'new'
  end

  def create
  	user = User.new(name: params[:user][:name], email: params[:user][:email])
  	if user.save
  		redirect_to user_path(user)
  	else
  		render :text => 'User could not be saved'
  	end
  end

  def destroy
  end
end

#Controller is plural

auction_site heroku/app/helpers/application_helper.rb
module ApplicationHelper
end

auction_site heroku/app/helpers/bids_helper.rb
module BidsHelper
	def show_name(user_id)
	 (User.find_by(id: user_id)).name 
	end

	def show_product(product_id)
		(Product.find_by(id: product_id)).title
	end
end
#Use these to help you with the view when you need to remove logic from the view

auction_site heroku/app/helpers/products_helper.rb
module ProductsHelper
	def show_name(user_id)
	 (User.find_by(id: user_id)).name 
	end

	def show_product(product_id)
		(Product.find_by(id: product_id)).title
	end

	def show_bid(bid_id)
		(Bid.find_by(id: bid_id)).user_id
	end

end

auction_site heroku/app/helpers/user_helper.rb
module UserHelper
end

auction_site heroku/app/views/bids/create.html.erb
<h1>Bids#create</h1>
<p>Find me in app/views/bids/create.html.erb</p>

auction_site heroku/app/views/bids/index.html.erb
<h1>Bids</h1>
	<% @bids.each do |bid|%>
		Bid by: <%= show_name(bid.user_id) %> for <%= show_product(bid.product_id)%> for $<%=bid.amount %><br>
<%end%>

auction_site heroku/app/views/bids/new.html.erb
<h1>Place a bid!</h1>
<h2>Good luck!</h2>


<%= form_tag (product_bids_path method: :post) do |f|%>
	<%= label_tag :email%>
	<%= text_field_tag :email%>
	<%= label_tag :amount%>
	<%= number_field_tag :amount%>
	<%= submit_tag "Bid!"%>
<% end %>

auction_site heroku/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuctionSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

auction_site heroku/app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

auction_site heroku/app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

auction_site heroku/app/views/products/index.html.erb
<h1>Products</h1>
	<% @products.each do |product|%>
		<strong><%=	link_to "#{product.title}", user_product_path(product.user_id, product.id)%></strong><br>
		<%=	product.description %><br>
		<%=	product.deadline %><br><br>
<%end%>

auction_site heroku/app/views/products/new.html.erb
<h1>Add a new product</h1>

<%= form_for [@user, @new_product] do |f|%>
<%= f.label :title%>
<%= f.text_field :title%>
<%= f.label :description%>
<%= f.text_field :description%><br><br>
<%= f.label :price%>
<%= f.text_field :min_bid%><br>
<%= f.label :deadline%>
<%= f.datetime_field :deadline%>
<%= f.button "Add product"%>

<%end%>

auction_site heroku/app/views/products/show.html.erb
<h1><%=@product.title%></h1>
Being sold by: <strong><%= @user.name %></strong>
<br>Description: <%= @product.description %>
<br>Price: $<%= @product.min_bid%>

<% if Date.today < @product.deadline %>
	<p><%= link_to "Place a bid", "/products/#{@product.id}/bids/new"%></p>
<% else %>
	<p>Product no longer available<br>
	Bid Winner is: <%= @winner%></p>
	
<% end %>



<!--IMPORTANCE OF INTERPOLATION 
the :id is not valid anywhere but the route
in any view, you need to put in within interpolation #{}
in order for the value to be valid>

auction_site heroku/app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

auction_site heroku/app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

auction_site heroku/app/views/users/new.html.erb
<h1>Sign up for Auction Site!</h1>

<%= form_for @new_user do |f|%>
<%= f.label :name%>
<%= f.text_field :name%>
<%= f.label :email%>
<%= f.text_field :email%>
<%= f.button "Register"%>

<%end%>

auction_site heroku/app/views/users/show.html.erb
<h1>Hello, <%=@user.name%></h1>
<p>your email is <%=@user.email%></p>